# Generated by Django 2.2.1 on 2020-03-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=0, max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='类别')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='头像')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.CharField(blank=True, max_length=4, null=True, verbose_name='性别')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('job_status', models.IntegerField(blank=True, null=True, verbose_name='职位状态信息')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
