# Generated by Django 2.2.1 on 2020-03-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0004_auto_20200317_1622'),
        ('Boss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='job_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boss.Job'),
        ),
    ]
