# Generated by Django 2.2.1 on 2020-03-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0005_check_job_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
