# Generated by Django 2.2.1 on 2020-03-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0006_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='username',
            new_name='name',
        ),
    ]
