# Generated by Django 2.2.1 on 2020-03-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0007_auto_20200318_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='type',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='类别'),
        ),
    ]
