# Generated by Django 2.2.1 on 2020-04-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0010_auto_20200329_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
