# Generated by Django 2.2.1 on 2020-03-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Boss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expect_job', models.CharField(max_length=64, verbose_name='意向岗位')),
                ('city', models.CharField(max_length=16, verbose_name='意向城市')),
                ('salary', models.CharField(max_length=16, verbose_name='期望薪资')),
                ('education', models.TextField(verbose_name='教育经历')),
                ('project', models.TextField(verbose_name='项目经历')),
                ('school_experience', models.TextField(verbose_name='在校经历')),
                ('self_introduction', models.TextField(verbose_name='自我介绍')),
                ('skill', models.TextField(verbose_name='相关技能')),
                ('honor', models.TextField(verbose_name='荣誉证书')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='投递时间')),
                ('send_status', models.IntegerField(choices=[(0, '已投递'), (1, '被查看'), (2, '不合符'), (3, '接受面试邀请'), (4, '拒绝面试邀请'), (5, '面试通过'), (6, '收到聘用协议')], verbose_name='投递状态')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boss.Job')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=0, max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='求职者名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('type', models.IntegerField(verbose_name='类别')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='头像')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(max_length=4, verbose_name='性别')),
                ('native', models.CharField(blank=True, max_length=32, null=True, verbose_name='籍贯')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graduate.Resume')),
            ],
            options={
                'db_table': 'hunter',
            },
        ),
    ]
