# Generated by Django 2.2.1 on 2020-03-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='gender',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='求职者名'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Graduate.Resume'),
        ),
    ]
