# Generated by Django 2.2.1 on 2020-03-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate', '0004_auto_20200320_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunter',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Graduate.Hunter'),
        ),
    ]
