# Generated by Django 2.2.1 on 2020-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate', '0007_auto_20200329_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='send_status',
            field=models.IntegerField(choices=[(0, '已投递'), (1, '不合符'), (2, '接受面试邀请'), (3, '拒绝面试邀请'), (4, '面试通过'), (5, '收到聘用协议')], verbose_name='投递状态'),
        ),
    ]
