# Generated by Django 2.2.1 on 2020-04-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate', '0009_auto_20200409_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boss.Job_table'),
        ),
        migrations.AlterField(
            model_name='process',
            name='send_status',
            field=models.IntegerField(choices=[(0, '已投递'), (1, '被查看'), (2, '接受面试邀请'), (3, '不符合'), (4, '拒绝面试邀请'), (5, '面试通过'), (6, '面试未通过'), (7, '收到聘用协议')], verbose_name='投递状态'),
        ),
    ]
