# Generated by Django 2.2.1 on 2020-04-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graduate', '0010_auto_20200409_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
