# Generated by Django 2.2.1 on 2020-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=0, max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='招聘者名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('type', models.IntegerField(blank=True, null=True, verbose_name='类别')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='头像')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.CharField(blank=True, max_length=4, null=True, verbose_name='性别')),
                ('address', models.TextField(blank=True, null=True, verbose_name='居住地')),
            ],
            options={
                'db_table': 'boss',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_email', models.EmailField(max_length=254, verbose_name='企业邮箱')),
                ('c_name', models.CharField(max_length=32, verbose_name='企业名')),
                ('phone_number', models.CharField(max_length=11, verbose_name='企业电话')),
                ('c_code', models.IntegerField(verbose_name='统一信用代码')),
                ('c_legal', models.CharField(max_length=32, verbose_name='企业法人')),
                ('c_photo', models.ImageField(upload_to='images', verbose_name='企业照片')),
                ('c_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='注册资本')),
                ('c_status', models.IntegerField(choices=[(0, '存续(开业、正常、登记)'), (1, '在业'), (2, '吊销'), (3, '注销'), (4, '迁出'), (5, '迁入'), (6, '停业'), (7, '清算')], verbose_name='经营状态')),
                ('c_time', models.DateTimeField(verbose_name='成立时间')),
                ('c_address', models.TextField(verbose_name='注册地址')),
                ('c_scope', models.TextField(verbose_name='经营范围')),
                ('c_website', models.TextField(verbose_name='公司官网')),
                ('c_descript', models.TextField(verbose_name='公司简介')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Hr_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.IntegerField(verbose_name='在职信息')),
                ('professional_title', models.CharField(max_length=32, verbose_name='职称')),
                ('work_experience', models.TextField(verbose_name='工作经验')),
            ],
            options={
                'db_table': 'hr_job',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=32, verbose_name='职位名称')),
                ('job_status', models.IntegerField(choices=[(0, '审核中'), (1, '已发布'), (2, '审核未通过')], verbose_name='职位状态')),
                ('job_address', models.TextField(verbose_name='工作地点')),
                ('education', models.IntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中'), (3, '大专'), (4, '本科'), (5, '硕士'), (6, '博士')], verbose_name='学历')),
                ('pay', models.CharField(max_length=20, verbose_name='薪资')),
                ('job_descript', models.TextField(blank=True, null=True, verbose_name='岗位详情')),
                ('demand', models.TextField(verbose_name='任职要求')),
                ('work_time', models.TextField(verbose_name='工作时间')),
                ('job_label', models.TextField(verbose_name='标签')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='job_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='投递时间')),
                ('send_status', models.IntegerField(choices=[(0, '未查看'), (1, '已查看'), (2, '面试邀请'), (3, '投递失败'), (4, '面试通过'), (5, '面试未通过'), (6, '聘用协议发送')], verbose_name='投递状态')),
            ],
            options={
                'db_table': 'job_table',
            },
        ),
    ]
