# Generated by Django 2.2.1 on 2020-03-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Graduate', '0001_initial'),
        ('Boss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_table',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graduate.Hunter'),
        ),
        migrations.AddField(
            model_name='job',
            name='b_boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boss.Boss'),
        ),
        migrations.AddField(
            model_name='job',
            name='j_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boss.Company'),
        ),
        migrations.AddField(
            model_name='boss',
            name='b_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boss.Company'),
        ),
        migrations.AddField(
            model_name='boss',
            name='b_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boss.Hr_job'),
        ),
    ]
