# Generated by Django 2.2.1 on 2020-03-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0002_auto_20200317_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_code',
            field=models.CharField(max_length=32, verbose_name='统一信用代码'),
        ),
    ]
