# Generated by Django 2.2.1 on 2020-03-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0006_auto_20200320_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[(0, '审核中'), (1, '已发布'), (2, '审核未通过')], max_length=4, verbose_name='职位状态'),
        ),
    ]
