# Generated by Django 2.2.1 on 2020-03-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0007_auto_20200320_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '已发布'), (2, '审核未通过')], verbose_name='职位状态'),
        ),
    ]
