# Generated by Django 2.2.1 on 2020-03-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0009_auto_20200320_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='b_resume',
        ),
        migrations.AddField(
            model_name='boss',
            name='professional_title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='职称'),
        ),
        migrations.AddField(
            model_name='boss',
            name='work_experience',
            field=models.TextField(blank=True, null=True, verbose_name='工作经验'),
        ),
        migrations.AddField(
            model_name='boss',
            name='work_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='在职信息'),
        ),
        migrations.DeleteModel(
            name='Hr_job',
        ),
    ]
