# Generated by Django 2.2.1 on 2020-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0011_auto_20200325_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_money',
            field=models.IntegerField(verbose_name='注册资本'),
        ),
    ]
