# Generated by Django 2.2.1 on 2020-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0012_auto_20200325_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_time',
            field=models.DateField(verbose_name='成立时间'),
        ),
    ]
