# Generated by Django 2.2.1 on 2020-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0013_auto_20200325_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_time',
            field=models.DateTimeField(verbose_name='成立时间'),
        ),
    ]
