# Generated by Django 2.2.1 on 2020-03-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0015_auto_20200325_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_table',
            old_name='name',
            new_name='h_name',
        ),
        migrations.AddField(
            model_name='job_table',
            name='j_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Boss.Job'),
        ),
    ]
