# Generated by Django 2.2.1 on 2020-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0016_auto_20200329_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核中'), (2, '已发布'), (3, '审核未通过')], verbose_name='职位状态'),
        ),
    ]
