# Generated by Django 2.2.1 on 2020-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0017_auto_20200402_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='发布时间'),
        ),
    ]
