# Generated by Django 2.2.1 on 2020-04-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0018_job_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='check_status',
            field=models.IntegerField(blank=True, choices=[(0, '待审核'), (1, '审核中'), (2, '已发布'), (3, '审核未通过'), (4, '已删除')], null=True, verbose_name='审核状态'),
        ),
    ]
