# Generated by Django 2.2.1 on 2020-04-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0021_auto_20200406_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_table',
            name='send_status',
            field=models.IntegerField(choices=[(0, '未查看'), (1, '已查看'), (2, '面试邀请'), (3, '已拒绝'), (4, '邀请面试失败'), (5, '面试通过'), (6, '面试未通过'), (7, '聘用协议发送')], verbose_name='投递状态'),
        ),
    ]
